# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.4.4'
gem 'dotenv'
gem 'http'
gem 'json'
gem 'nokogiri'
gem 'open-uri'
gem 'pry'
gem 'reline'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'watir'
